package goclocbudget

import (
	"os"
	"path/filepath"
	"testing"
)

func TestCountExcludesTestsGeneratedAndConfiguredDirs(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "main.go", "package main\n\nfunc main() {\n\tprintln(\"ok\")\n}\n")
	writeTestFile(t, root, "main_test.go", "package main\n\nfunc TestMain(t *testing.T) {\n}\n")
	writeTestFile(t, root, "generated.go", "// Code generated by test. DO NOT EDIT.\npackage main\n\nfunc generated() {\n}\n")
	writeTestFile(t, root, "vendor/ignored.go", "package vendor\n\nfunc ignored() {\n}\n")

	excludeGenerated := true
	p := plugin{settings: settings{
		MaxGoCodeLines:   1,
		ExcludeGenerated: &excludeGenerated,
		ExcludeDirs:      []string{"vendor"},
	}}
	result, err := p.count(root)
	if err != nil {
		t.Fatalf("count returned error: %v", err)
	}
	if result.code != 4 {
		t.Fatalf("code lines = %d, want 4", result.code)
	}
	if len(result.largest) != 1 || result.largest[0] != "main.go=4" {
		t.Fatalf("largest = %#v", result.largest)
	}
}

func TestModuleRootFindsParent(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "go.mod", "module example.com/test\n")
	nested := filepath.Join(root, "cmd", "tool")
	if err := os.MkdirAll(nested, 0o700); err != nil {
		t.Fatal(err)
	}
	got, err := moduleRoot(nested)
	if err != nil {
		t.Fatal(err)
	}
	if got != root {
		t.Fatalf("moduleRoot = %q, want %q", got, root)
	}
}

func TestNewExcludesGeneratedByDefault(t *testing.T) {
	created, err := New(map[string]any{"max-go-code-lines": 1})
	if err != nil {
		t.Fatal(err)
	}
	p := created.(*plugin)
	if p.settings.ExcludeGenerated != nil {
		t.Fatal("unset exclude-generated should use the default")
	}
}

func writeTestFile(t *testing.T, root string, name string, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}
